# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: library.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x06protos\"\xbe\x01\n\x04\x42ook\x12\x0c\n\x04isbn\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12!\n\x05genre\x18\x04 \x01(\x0e\x32\x12.protos.Book.Genre\x12\x14\n\x0cpublish_year\x18\x05 \x01(\x05\"P\n\x05Genre\x12\x0b\n\x07ROMANCE\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\x0b\n\x07MYSTERY\x10\x02\x12\r\n\tBIOGRAPHY\x10\x03\x12\t\n\x05OTHER\x10\x04\"o\n\rInventoryItem\x12\x14\n\x0cinventory_id\x18\x01 \x01(\x05\x12\x1c\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x0c.protos.BookH\x00\"\"\n\x06status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\x06\n\x04type\"/\n\x11\x43reateBookRequest\x12\x1a\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0c.protos.Book\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"-\n\x0fGetBookResponse\x12\x1a\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0c.protos.Book\"%\n\x12\x43reateBookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x97\x01\n\x10InventoryService\x12\x45\n\nCreateBook\x12\x19.protos.CreateBookRequest\x1a\x1a.protos.CreateBookResponse\"\x00\x12<\n\x07GetBook\x12\x16.protos.GetBookRequest\x1a\x17.protos.GetBookResponse\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=26
  _BOOK._serialized_end=216
  _BOOK_GENRE._serialized_start=136
  _BOOK_GENRE._serialized_end=216
  _INVENTORYITEM._serialized_start=218
  _INVENTORYITEM._serialized_end=329
  _INVENTORYITEM_STATUS._serialized_start=287
  _INVENTORYITEM_STATUS._serialized_end=321
  _CREATEBOOKREQUEST._serialized_start=331
  _CREATEBOOKREQUEST._serialized_end=378
  _GETBOOKREQUEST._serialized_start=380
  _GETBOOKREQUEST._serialized_end=410
  _GETBOOKRESPONSE._serialized_start=412
  _GETBOOKRESPONSE._serialized_end=457
  _CREATEBOOKRESPONSE._serialized_start=459
  _CREATEBOOKRESPONSE._serialized_end=496
  _INVENTORYSERVICE._serialized_start=499
  _INVENTORYSERVICE._serialized_end=650
# @@protoc_insertion_point(module_scope)
